// Generated by create-pet-skill — desktop pet main process
const { app, BrowserWindow, ipcMain, Menu, screen, globalShortcut, Tray, nativeImage } = require('electron');
const path = require('path');
const fs = require('fs');

// ---- baked constants ----
const APP_NAME = "isla";
const STAGE_WIDTH = 355;
const STAGE_HEIGHT = 472;
const HAS_ACTION = {"idle-buddy":true,"typing":true,"cheer-up":true,"drink-water":true,"rest-reminder":true,"off-work":true,"poke-react":true,"celebrate":true,"sleep":true,"new-message":true,"date-weather":true};

app.setName(APP_NAME); // keep userData path stable between dev and packaged runs
// 透明置顶小窗口走软件渲染即可；部分 Windows 环境 GPU 进程会在启动/缩放重绘时崩溃弹窗
app.disableHardwareAcceleration();
// 单实例：重复双击启动.bat 时直接退出新实例，避免多开互相抢快捷键/输入钩子
if (!app.requestSingleInstanceLock()) {
  console.log('[pet] 已在运行，本次启动自动退出');
  process.exit(0);
}

// ---- optional native modules (graceful degradation, never crash) ----
let uiohook = null;
try {
  uiohook = require('uiohook-napi');
  // uiohook-napi exports { uIOhook, UiohookKey } — normalize to the instance
  uiohook = uiohook.uIOhook || uiohook;
} catch (e) {
  console.warn('[pet] uiohook-napi 不可用，键盘/鼠标镜像与全局视线跟随将降级：', e.message);
}
let activeWinMod = null;
(async () => {
  try {
    activeWinMod = await import('active-win');
  } catch (e) {
    console.warn('[pet] active-win 不可用，游戏模式自动降透明度将降级：', e.message);
  }
})();

// ---- small utils ----
function clamp(v, min, max) {
  return Math.min(max, Math.max(min, v));
}

function debounce(fn, ms) {
  let t = null;
  return function () {
    const args = arguments;
    if (t) clearTimeout(t);
    t = setTimeout(function () { t = null; fn.apply(null, args); }, ms);
  };
}

// ---- settings store (userData) ----
const userDataDir = app.getPath('userData');
const DEFAULT_SETTINGS = {
  version: 1,
  autoScaleRatio: 0.2,
  zoom: 1,
  opacity: 1,
  clickThrough: false,
  gameMode: true,
  gameModeOpacity: 0.35,
  inputMirror: true,
  position: null,
};

function loadJson(name, fallback) {
  try {
    const p = path.join(userDataDir, name);
    if (!fs.existsSync(p)) return fallback;
    return Object.assign({}, fallback, JSON.parse(fs.readFileSync(p, 'utf-8')));
  } catch (e) {
    try {
      fs.renameSync(path.join(userDataDir, name), path.join(userDataDir, name + '.bak'));
    } catch (e2) { /* ignore */ }
    return fallback;
  }
}

let settings = loadJson('settings.json', DEFAULT_SETTINGS);
// 穿透模式只对本次运行生效（不落盘）：误开穿透导致点不到桌宠时，重启即恢复
settings.clickThrough = false;
let pendingSettingsSave = null;

function saveSettings() {
  if (pendingSettingsSave) return;
  pendingSettingsSave = setTimeout(function () {
    pendingSettingsSave = null;
    try {
      fs.mkdirSync(userDataDir, { recursive: true });
      const toSave = Object.assign({}, settings);
      toSave.clickThrough = false;
      fs.writeFileSync(path.join(userDataDir, 'settings.json'), JSON.stringify(toSave, null, 2));
    } catch (e) {
      console.warn('[pet] 设置写入失败：', e.message);
    }
  }, 500);
}

function broadcastSettings() {
  saveSettings();
  if (petWindow && !petWindow.isDestroyed()) {
    petWindow.webContents.send('settings-changed', settings);
  }
}

// ---- windows ----
let petWindow = null;
let tray = null;
let isFullscreenNow = false;
let lastDisplayKey = null;

// Same formula as the renderer's — used only to pre-size the window at startup
function computeScale(workAreaHeight, s) {
  const ratio = clamp(s.autoScaleRatio != null ? s.autoScaleRatio : 0.2, 0.08, 0.45);
  const targetH = clamp(workAreaHeight * ratio, 80, Math.min(420, workAreaHeight * 0.5));
  return (targetH * clamp(s.zoom != null ? s.zoom : 1, 0.5, 2.5)) / STAGE_HEIGHT;
}

function restorePosition(width, height) {
  const pos = settings.position;
  let d = null;
  if (pos && pos.displayId) {
    d = screen.getAllDisplays().find(function (dd) { return dd.id === pos.displayId; }) || null;
  }
  if (!d) d = screen.getPrimaryDisplay();
  const wa = d.workArea;
  let x, y;
  if (pos && pos.rx != null && pos.ry != null) {
    x = wa.x + pos.rx * Math.max(wa.width - width, 1);
    y = wa.y + pos.ry * Math.max(wa.height - height, 1);
  } else {
    x = wa.x + wa.width - width - 80;
    y = wa.y + Math.round(wa.height * 0.55);
  }
  return { x: Math.round(x), y: Math.round(y), displayId: d.id };
}

function clampToWorkArea(b) {
  // 参数先做数值化防护：渲染层可能传入非法值，直接进原生 API 会弹「conversion failure」报错
  const x0 = Number(b.x);
  const y0 = Number(b.y);
  const w0 = Number(b.width) || STAGE_WIDTH;
  const h0 = Number(b.height) || STAGE_HEIGHT;
  const d = screen.getDisplayMatching({ x: isFinite(x0) ? x0 : 0, y: isFinite(y0) ? y0 : 0, width: w0, height: h0 });
  const wa = d.workArea;
  const x = clamp(isFinite(x0) ? x0 : 0, wa.x - w0 + 40, wa.x + wa.width - 40);
  let y;
  if (wa.height - 40 < h0) {
    y = wa.y;
  } else {
    y = clamp(isFinite(y0) ? y0 : 0, wa.y, wa.y + wa.height - 40);
  }
  return { x: Math.round(x), y: Math.round(y), width: w0, height: h0 };
}

function createWindow() {
  let d = null;
  if (settings.position && settings.position.displayId) {
    d = screen.getAllDisplays().find(function (dd) { return dd.id === settings.position.displayId; }) || null;
  }
  if (!d) d = screen.getPrimaryDisplay();
  const scale = computeScale(d.workArea.height, settings);
  const width = Math.round(STAGE_WIDTH * scale);
  const height = Math.round(STAGE_HEIGHT * scale);
  const pos = restorePosition(width, height);
  petWindow = new BrowserWindow({
    x: pos.x, y: pos.y,
    width: width, height: height,
    transparent: true, frame: false, alwaysOnTop: true,
    skipTaskbar: false, resizable: false, hasShadow: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true, nodeIntegration: false,
    },
  });
  petWindow.loadFile(path.join(__dirname, 'renderer', 'index.html'));
  petWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  petWindow.setAlwaysOnTop(true, 'screen-saver');
  petWindow.setIgnoreMouseEvents(settings.clickThrough, { forward: true });
  petWindow.on('closed', function () { petWindow = null; });
  petWindow.on('move', debounce(function () { checkDisplayChange(); savePosition(); }, 300));
}

function currentDisplayConfig() {
  const d = petWindow ? screen.getDisplayMatching(petWindow.getBounds()) : screen.getPrimaryDisplay();
  return {
    displayId: d.id,
    workArea: { x: d.workArea.x, y: d.workArea.y, width: d.workArea.width, height: d.workArea.height },
    scaleFactor: d.scaleFactor,
  };
}

function checkDisplayChange() {
  const cfg = currentDisplayConfig();
  const key = cfg.displayId + ':' + cfg.workArea.width + 'x' + cfg.workArea.height;
  if (key !== lastDisplayKey) {
    lastDisplayKey = key;
    if (petWindow && !petWindow.isDestroyed()) {
      petWindow.webContents.send('display-config-changed', cfg);
    }
  }
}

function savePosition() {
  if (!petWindow || petWindow.isDestroyed()) return;
  const [x, y] = petWindow.getPosition();
  const [w, h] = petWindow.getSize();
  const d = screen.getDisplayMatching({ x: x, y: y, width: w, height: h });
  const wa = d.workArea;
  settings.position = {
    displayId: d.id,
    rx: (x - wa.x) / Math.max(wa.width - w, 1),
    ry: (y - wa.y) / Math.max(wa.height - h, 1),
  };
  saveSettings();
}

// ---- context menu ----
function sendCommand(cmd) {
  if (petWindow && !petWindow.isDestroyed()) {
    petWindow.webContents.send('pet-command', cmd);
  }
}

function setClickThrough(v) {
  settings.clickThrough = v;
  broadcastSettings();
  if (petWindow && !petWindow.isDestroyed()) {
    petWindow.setIgnoreMouseEvents(v, { forward: true });
  }
}

function applyOpacity() {
  if (petWindow && !petWindow.isDestroyed()) {
    petWindow.setOpacity(isFullscreenNow ? settings.gameModeOpacity : settings.opacity);
  }
}

function setOpacity(v) {
  settings.opacity = clamp(v, 0.3, 1);
  broadcastSettings();
  applyOpacity();
}

function resetPosition() {
  if (!petWindow || petWindow.isDestroyed()) return;
  const wa = screen.getPrimaryDisplay().workArea;
  const [w, h] = petWindow.getSize();
  petWindow.setBounds(clampToWorkArea({ x: wa.x + wa.width - w - 80, y: wa.y + wa.height - h - 40, width: w, height: h }));
  savePosition();
}

function toggleVisible() {
  if (!petWindow || petWindow.isDestroyed()) return;
  if (petWindow.isVisible()) petWindow.hide();
  else petWindow.show();
}

function createContextMenu(currentActionId) {
  const actions = [
    { id: "idle-buddy", label: "陪班待机" },
    { id: "typing", label: "敲键盘" },
    { id: "cheer-up", label: "傲娇打气" },
    { id: "drink-water", label: "喝水提醒" },
    { id: "rest-reminder", label: "休息提醒" },
    { id: "off-work", label: "下班提醒" },
    { id: "poke-react", label: "戳一戳撒娇" },
    { id: "celebrate", label: "完成任务庆祝" },
    { id: "sleep", label: "睡觉挂机" },
    { id: "new-message", label: "消息提醒" },
    { id: "date-weather", label: "日期天气播报" },
  ];
  const items = actions.map(function (a) {
    return {
      label: a.id === currentActionId ? '\u2713 ' + a.label : a.label,
      click: function () {
        if (petWindow) petWindow.webContents.send('switch-action', a.id);
      },
    };
  });
  items.push({ type: 'separator' });
  items.push({ label: '放大 (Ctrl+Shift+\u2192)', click: function () { sendCommand('zoom-in'); } });
  items.push({ label: '缩小 (Ctrl+Shift+\u2190)', click: function () { sendCommand('zoom-out'); } });
  items.push({ label: '恢复默认大小', click: function () { settings.zoom = 1; broadcastSettings(); } });
  items.push({ type: 'separator' });
  items.push({
    label: (settings.clickThrough ? '\u2713 ' : '') + '穿透模式 (Ctrl+Shift+X)',
    click: function () { setClickThrough(!settings.clickThrough); },
  });
  items.push({
    label: (settings.gameMode ? '\u2713 ' : '') + '游戏模式自动降透明度',
    click: function () { settings.gameMode = !settings.gameMode; broadcastSettings(); applyOpacity(); },
  });
  items.push({ type: 'separator' });
  items.push({ label: '\u9000\u51fa', click: function () { app.quit(); } });
  return Menu.buildFromTemplate(items);
}

// ---- tray icon (fallback entry when click-through is on) ----
function createTray() {
  try {
    const iconPath = path.join(__dirname, 'assets', 'icon.png');
    const img = nativeImage.createFromPath(iconPath);
    const small = img.isEmpty() ? img : img.resize({ width: 16, height: 16 });
    tray = new Tray(small);
    tray.setToolTip(APP_NAME);
    tray.setContextMenu(Menu.buildFromTemplate([
      { label: '显示/隐藏', click: toggleVisible },
      { type: 'separator' },
      { label: '\u9000\u51fa', click: function () { app.quit(); } },
    ]));
    tray.on('click', toggleVisible);
  } catch (e) {
    console.warn('[pet] 托盘创建失败：', e.message);
  }
}

// ---- game mode: fullscreen detection -> lower opacity ----
async function pollGameMode() {
  if (!activeWinMod || !petWindow || petWindow.isDestroyed()) return;
  try {
    const getWin = activeWinMod.default || activeWinMod;
    const w = await getWin();
    if (!w || !w.bounds) return;
    const d = screen.getDisplayMatching(w.bounds);
    const wa = d.workArea;
    const covers = w.bounds.width * w.bounds.height >= wa.width * wa.height * 0.95 &&
      Math.abs(w.bounds.x - wa.x) <= 12 && Math.abs(w.bounds.y - wa.y) <= 12;
    const isShell = /explorer|desktop|progman/i.test((w.owner && w.owner.name) || '');
    const fullscreen = covers && !isShell && settings.gameMode;
    if (fullscreen !== isFullscreenNow) {
      isFullscreenNow = fullscreen;
      applyOpacity();
    }
  } catch (e) { /* ignore polling errors */ }
}
setInterval(pollGameMode, 3000);

// ---- global input mirror (uiohook) ----
function initInputCapture() {
  if (!uiohook || !settings.inputMirror) return;
  let lastKeySentAt = 0;
  let lastKeyEventAt = 0;
  let lastClickSentAt = 0;
  let lastMoveSentAt = 0;
  try {
    uiohook.on('keydown', function () {
      const now = Date.now();
      if (now - lastKeyEventAt > 2000) lastKeySentAt = 0; // typing paused 2s -> reset cooldown
      lastKeyEventAt = now;
      if (now - lastKeySentAt >= 6000 && petWindow && !petWindow.isDestroyed()) {
        lastKeySentAt = now;
        petWindow.webContents.send('input-event', { type: 'keydown' });
      }
    });
    uiohook.on('keyup', function () {
      lastKeyEventAt = Date.now();
    });
    uiohook.on('mousedown', function (e) {
      const now = Date.now();
      if (now - lastClickSentAt < 3000 || !petWindow || petWindow.isDestroyed()) return;
      const b = petWindow.getBounds();
      // clicks on the pet itself are handled by her own click handlers
      if (e.x >= b.x && e.x <= b.x + b.width && e.y >= b.y && e.y <= b.y + b.height) return;
      lastClickSentAt = now;
      petWindow.webContents.send('input-event', { type: 'mouse-down', button: e.button });
    });
    uiohook.on('mousemove', function (e) {
      const now = Date.now();
      if (now - lastMoveSentAt < 40 || !petWindow || petWindow.isDestroyed()) return;
      lastMoveSentAt = now;
      petWindow.webContents.send('pointer-move', { x: e.x, y: e.y, winBounds: petWindow.getBounds() });
    });
    uiohook.start();
    console.log('[pet] 输入镜像已启用');
  } catch (e) {
    console.warn('[pet] 输入镜像启动失败：', e.message);
    uiohook = null;
  }
}

// ---- IPC ----
ipcMain.on('show-context-menu', function (_event, currentActionId) {
  const menu = createContextMenu(currentActionId);
  menu.popup({ window: petWindow });
});

ipcMain.on('resize-window', function (_event, width, height) {
  if (!petWindow) return;
  width = Number(width);
  height = Number(height);
  if (!isFinite(width) || !isFinite(height) || width <= 0 || height <= 0) return;
  const [x, y] = petWindow.getPosition();
  const [w, h] = petWindow.getSize();
  // horizontal centering + bottom anchor (feet stay put, no jumping)
  petWindow.setBounds(clampToWorkArea({
    x: x + (w - width) / 2,
    y: y + (h - height),
    width: Math.round(width),
    height: Math.round(height),
  }));
});

ipcMain.on('move-window', function (_event, dx, dy, opts) {
  if (!petWindow) return;
  dx = Number(dx);
  dy = Number(dy);
  if (!isFinite(dx) || !isFinite(dy)) return;
  const [x, y] = petWindow.getPosition();
  let nx = x + dx;
  let ny = y + dy;
  if (opts && opts.clamp) {
    const [w, h] = petWindow.getSize();
    const b = clampToWorkArea({ x: nx, y: ny, width: w, height: h });
    nx = b.x;
    ny = b.y;
  }
  petWindow.setPosition(Math.round(nx), Math.round(ny));
});

ipcMain.handle('get-display-config', function () {
  return currentDisplayConfig();
});

ipcMain.handle('settings-get', function () {
  return settings;
});

ipcMain.on('settings-set', function (_event, patch) {
  if (!patch || typeof patch !== 'object') return;
  for (const k of Object.keys(patch)) settings[k] = patch[k];
  broadcastSettings();
});

ipcMain.handle('capabilities-get', function () {
  return {
    inputCapture: !!uiohook,
    gameModeSupport: !!activeWinMod,
    fullscreenNow: isFullscreenNow,
    clickThrough: settings.clickThrough,
    opacity: settings.opacity,
  };
});

ipcMain.on('set-click-through', function (_event, v) {
  setClickThrough(!!v);
});

ipcMain.on('set-opacity', function (_event, v) {
  setOpacity(v);
});

ipcMain.on('quit-app', function () {
  app.quit();
});

// ---- global shortcuts ----
function registerShortcuts() {
  const SHORTCUTS = [
    ['Ctrl+Shift+B', toggleVisible],
    ['Ctrl+Shift+Left', function () { sendCommand('zoom-out'); }],
    ['Ctrl+Shift+Right', function () { sendCommand('zoom-in'); }],
    ['Ctrl+Shift+Up', function () { setOpacity(settings.opacity + 0.1); }],
    ['Ctrl+Shift+Down', function () { setOpacity(settings.opacity - 0.1); }],
    ['Ctrl+Shift+R', resetPosition],
    ['Ctrl+Shift+Q', function () { app.quit(); }],
    ['Ctrl+Shift+X', function () { setClickThrough(!settings.clickThrough); }],
  ];
  for (const pair of SHORTCUTS) {
    if (!globalShortcut.register(pair[0], pair[1])) {
      console.warn('[pet] 快捷键注册失败（可能被其他程序占用）：' + pair[0]);
    }
  }
}

// ---- app lifecycle ----
app.whenReady().then(function () {
  createWindow();
  createTray();
  initInputCapture();
  registerShortcuts();
  screen.on('display-added', checkDisplayChange);
  screen.on('display-removed', checkDisplayChange);
  screen.on('display-metrics-changed', checkDisplayChange);
  app.on('activate', function () {
    if (BrowserWindow.getAllWindows().length === 0) createWindow();
  });
});

app.on('before-quit', function () {
  try {
    if (uiohook) uiohook.stop();
  } catch (e) { /* ignore */ }
  globalShortcut.unregisterAll();
  if (pendingSettingsSave) {
    clearTimeout(pendingSettingsSave);
    pendingSettingsSave = null;
  }
  try {
    fs.mkdirSync(userDataDir, { recursive: true });
    fs.writeFileSync(path.join(userDataDir, 'settings.json'), JSON.stringify(settings, null, 2));
  } catch (e) { /* ignore */ }
});

app.on('window-all-closed', function () {
  app.quit();
});
