import fs from 'fs/promises';
import path from 'path';
import { fileURLToPath } from 'url';
import { exec, execFile } from 'child_process';
import { promisify } from 'util';
import sharp from 'sharp';

const execAsync = promisify(exec);
const execFileAsync = promisify(execFile);

interface ActionDefinition {
  id: string;
  name: string;
  frames: number;
  fps: number;
  description: string;
  prompt: string | null;
  spriteReady: boolean;
  frameWidth: number | null;
  frameHeight: number | null;
}

function parseArgs(argv: string[]): Record<string, string> {
  const args: Record<string, string> = {};
  for (let i = 2; i < argv.length; i++) {
    if (argv[i] === '--build') {
      args['build'] = 'true';
    } else if (argv[i].startsWith('--') && i + 1 < argv.length) {
      args[argv[i].slice(2)] = argv[++i];
    }
  }
  return args;
}

function generateActionsJs(actions: ActionDefinition[]): string {
  const entries = actions
    .map(
      (a) => `  ${JSON.stringify(a.id)}: {
    id: ${JSON.stringify(a.id)},
    name: ${JSON.stringify(a.name)},
    frames: ${a.frames},
    fps: ${a.fps},
    frameWidth: ${a.frameWidth || 256},
    frameHeight: ${a.frameHeight || 1024},
    loop: true,
    nextAction: null,
  }`
    )
    .join(',\n');

  // Semantic actions (input mirror, feeding, sleep) must not be played randomly;
  // sleep is taken over by the idle auto-sleep behavior.
  const SEMANTIC_ACTIONS = ['idle', 'typing', 'sleep'];
  const transitions = actions
    .filter((a) => !SEMANTIC_ACTIONS.includes(a.id))
    .map((a) => JSON.stringify(a.id))
    .join(', ');

  return `// DISPLAY_SCALE is only a fallback for environments without the Electron
// main process (e.g. plain browser preview). In the real app the pet auto-fits
// the screen height and this constant is ignored.
const DISPLAY_SCALE = 0.32;
const STAGE_WIDTH = ${Math.max(...actions.map((a) => a.frameWidth || 256))};
const STAGE_HEIGHT = ${Math.max(...actions.map((a) => a.frameHeight || 1024))};

const ACTIONS = {
${entries}
};

const IDLE_TRANSITIONS = [${transitions}];
`;
}

function generateMainJs(actions: ActionDefinition[], persona: unknown, appName: string): string {
  // typing 是输入镜像专用动作（现在由独立的键盘模式窗口播放），不进右键动作菜单
  const menuItems = actions
    .filter((a) => a.id !== 'typing')
    .map((a) => `    { id: ${JSON.stringify(a.id)}, label: ${JSON.stringify(a.name)} },`)
    .join('\n');

  const appNameJson = JSON.stringify(appName);
  const stageWidth = Math.max(...actions.map((a) => a.frameWidth || 256));
  const stageHeight = Math.max(...actions.map((a) => a.frameHeight || 1024));
  const hasActionTable = JSON.stringify(Object.fromEntries(actions.map((a) => [a.id, true])));

  return `// Generated by create-pet-skill — desktop pet main process
const { app, BrowserWindow, ipcMain, Menu, screen, globalShortcut, Tray, nativeImage } = require('electron');
const path = require('path');
const fs = require('fs');

// ---- baked constants ----
const APP_NAME = ${appNameJson};
const STAGE_WIDTH = ${stageWidth};
const STAGE_HEIGHT = ${stageHeight};
const HAS_ACTION = ${hasActionTable};

app.setName(APP_NAME); // keep userData path stable between dev and packaged runs
// 透明置顶小窗口走软件渲染即可；部分 Windows 环境 GPU 进程会在启动/缩放重绘时崩溃弹窗
app.disableHardwareAcceleration();

// ---- optional native modules (graceful degradation, never crash) ----
let uiohook = null;
try {
  uiohook = require('uiohook-napi');
  // uiohook-napi exports { uIOhook, UiohookKey } — normalize to the instance
  uiohook = uiohook.uIOhook || uiohook;
} catch (e) {
  console.warn('[pet] uiohook-napi 不可用，键盘/鼠标镜像与全局视线跟随将降级：', e.message);
}
// ---- small utils ----
function clamp(v, min, max) {
  return Math.min(max, Math.max(min, v));
}

function debounce(fn, ms) {
  let t = null;
  return function () {
    const args = arguments;
    if (t) clearTimeout(t);
    t = setTimeout(function () { t = null; fn.apply(null, args); }, ms);
  };
}

// ---- settings store (userData) ----
const userDataDir = app.getPath('userData');

// ---- 错误日志：未捕获异常默认会弹「A JavaScript error occurred」对话框，
// 这里拦截后写入 userData/error.log（含完整堆栈），既不打扰用户又能排查问题
function logError(tag, err) {
  try {
    const line = '[' + new Date().toISOString() + '] ' + tag + '\\n' + (err && err.stack ? err.stack : String(err)) + '\\n\\n';
    fs.appendFileSync(path.join(userDataDir, 'error.log'), line);
  } catch (e) { /* ignore */ }
}
process.on('uncaughtException', function (err) {
  logError('uncaughtException', err);
  console.error('[pet] uncaughtException:', err && err.stack ? err.stack : err);
});
process.on('unhandledRejection', function (err) {
  logError('unhandledRejection', err);
  console.error('[pet] unhandledRejection:', err);
});
app.on('child-process-gone', function (_e, details) {
  if (details && details.reason === 'clean-exit') return;
  logError('child-process-gone', JSON.stringify(details));
});

// 启动步骤日志：主进程卡在哪一步，error.log 里一眼可见
function logStep(msg) {
  logError('step', msg);
}

// 渲染进程崩溃/加载失败/报错 → error.log（这类错误默认静默不可见）
function attachErrorCapture(win, tag) {
  if (!win || win.isDestroyed()) return;
  win.webContents.on('render-process-gone', function (_e, details) {
    logError(tag + ':render-process-gone', JSON.stringify(details));
  });
  win.webContents.on('did-fail-load', function (_e, code, desc, url) {
    logError(tag + ':did-fail-load', code + ' ' + desc + ' ' + url);
  });
  win.webContents.on('console-message', function (_e, level, message, line, sourceId) {
    if (level >= 3) logError(tag + ':console', message + ' (' + sourceId + ':' + line + ')');
  });
}

// 单实例：重复双击启动.bat 时直接退出新实例，避免多开互相抢快捷键/输入钩子
// （放在 logError 之后，退出前能留一行日志）
if (!app.requestSingleInstanceLock()) {
  logStep('second-instance-exit');
  console.log('[pet] 已在运行，本次启动自动退出');
  process.exit(0);
}
app.on('second-instance', function () {
  logStep('second-instance-event');
  if (petWindow && !petWindow.isDestroyed()) petWindow.show();
});
logStep('app-start pid=' + process.pid);
const DEFAULT_SETTINGS = {
  version: 1,
  autoScaleRatio: 0.2,
  zoom: 1,
  opacity: 1,
  inputMirror: true,
  keyboardMode: true,
  position: null,
};

function loadJson(name, fallback) {
  try {
    const p = path.join(userDataDir, name);
    if (!fs.existsSync(p)) return fallback;
    return Object.assign({}, fallback, JSON.parse(fs.readFileSync(p, 'utf-8')));
  } catch (e) {
    try {
      fs.renameSync(path.join(userDataDir, name), path.join(userDataDir, name + '.bak'));
    } catch (e2) { /* ignore */ }
    return fallback;
  }
}

let settings = loadJson('settings.json', DEFAULT_SETTINGS);
let pendingSettingsSave = null;

function saveSettings() {
  if (pendingSettingsSave) return;
  pendingSettingsSave = setTimeout(function () {
    pendingSettingsSave = null;
    try {
      fs.mkdirSync(userDataDir, { recursive: true });
      fs.writeFileSync(path.join(userDataDir, 'settings.json'), JSON.stringify(settings, null, 2));
    } catch (e) {
      console.warn('[pet] 设置写入失败：', e.message);
    }
  }, 500);
}

function broadcastSettings() {
  saveSettings();
  if (petWindow && !petWindow.isDestroyed()) {
    petWindow.webContents.send('settings-changed', settings);
  }
}

// ---- windows ----
let petWindow = null;
let keyboardWindow = null;
let tray = null;
let lastDisplayKey = null;

// Same formula as the renderer's — used only to pre-size the window at startup
function computeScale(workAreaHeight, s) {
  const ratio = clamp(s.autoScaleRatio != null ? s.autoScaleRatio : 0.2, 0.08, 0.45);
  const targetH = clamp(workAreaHeight * ratio, 80, Math.min(420, workAreaHeight * 0.5));
  return (targetH * clamp(s.zoom != null ? s.zoom : 1, 0.5, 2.5)) / STAGE_HEIGHT;
}

function restorePosition(width, height) {
  const pos = settings.position;
  let d = null;
  if (pos && pos.displayId) {
    d = screen.getAllDisplays().find(function (dd) { return dd.id === pos.displayId; }) || null;
  }
  if (!d) d = screen.getPrimaryDisplay();
  const wa = d.workArea;
  let x, y;
  if (pos && pos.rx != null && pos.ry != null) {
    x = wa.x + pos.rx * Math.max(wa.width - width, 1);
    y = wa.y + pos.ry * Math.max(wa.height - height, 1);
  } else {
    x = wa.x + wa.width - width - 80;
    y = wa.y + Math.round(wa.height * 0.55);
  }
  return { x: Math.round(x), y: Math.round(y), displayId: d.id };
}

// getDisplayMatching 在个别 Windows 环境（启动瞬间/DPI 变化时）会抛
// 「Error processing argument at index 0, conversion failure」——捕获后回退主显示器，
// 现场写进 error.log，不再弹系统错误对话框
function safeDisplayMatching(bounds) {
  try {
    // getDisplayMatching 要求整数参数：渲染层算出的坐标常带 .5 小数（窗口居中除 2），
    // 直接传入会抛「conversion failure」——先取整
    return screen.getDisplayMatching({
      x: Math.round(Number(bounds.x) || 0),
      y: Math.round(Number(bounds.y) || 0),
      width: Math.round(Number(bounds.width) || 0),
      height: Math.round(Number(bounds.height) || 0),
    });
  } catch (e) {
    logError('getDisplayMatching failed, bounds=' + JSON.stringify(bounds), e);
    return screen.getPrimaryDisplay();
  }
}

function clampToWorkArea(b) {
  // 参数先做数值化防护：渲染层可能传入非法值，直接进原生 API 会弹「conversion failure」报错
  const x0 = Number(b.x);
  const y0 = Number(b.y);
  const w0 = Number(b.width) || STAGE_WIDTH;
  const h0 = Number(b.height) || STAGE_HEIGHT;
  const d = safeDisplayMatching({ x: isFinite(x0) ? x0 : 0, y: isFinite(y0) ? y0 : 0, width: w0, height: h0 });
  const wa = d.workArea;
  const x = clamp(isFinite(x0) ? x0 : 0, wa.x - w0 + 40, wa.x + wa.width - 40);
  let y;
  if (wa.height - 40 < h0) {
    y = wa.y;
  } else {
    y = clamp(isFinite(y0) ? y0 : 0, wa.y, wa.y + wa.height - 40);
  }
  return { x: Math.round(x), y: Math.round(y), width: w0, height: h0 };
}

function createWindow() {
  let d = null;
  if (settings.position && settings.position.displayId) {
    d = screen.getAllDisplays().find(function (dd) { return dd.id === settings.position.displayId; }) || null;
  }
  if (!d) d = screen.getPrimaryDisplay();
  const scale = computeScale(d.workArea.height, settings);
  const width = Math.round(STAGE_WIDTH * scale);
  const height = Math.round(STAGE_HEIGHT * scale);
  const pos = restorePosition(width, height);
  petWindow = new BrowserWindow({
    x: pos.x, y: pos.y,
    width: width, height: height,
    transparent: true, frame: false, alwaysOnTop: true,
    skipTaskbar: false, resizable: false, hasShadow: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true, nodeIntegration: false,
    },
  });
  petWindow.loadFile(path.join(__dirname, 'renderer', 'index.html'));
  attachErrorCapture(petWindow, 'pet');
  petWindow.setVisibleOnAllWorkspaces(true, { visibleOnFullScreen: true });
  petWindow.setAlwaysOnTop(true, 'screen-saver');
  petWindow.on('closed', function () { petWindow = null; });
  petWindow.on('move', debounce(function () { checkDisplayChange(); savePosition(); }, 300));
}

function currentDisplayConfig() {
  const d = petWindow ? safeDisplayMatching(petWindow.getBounds()) : screen.getPrimaryDisplay();
  return {
    displayId: d.id,
    workArea: { x: d.workArea.x, y: d.workArea.y, width: d.workArea.width, height: d.workArea.height },
    scaleFactor: d.scaleFactor,
  };
}

function checkDisplayChange() {
  const cfg = currentDisplayConfig();
  const key = cfg.displayId + ':' + cfg.workArea.width + 'x' + cfg.workArea.height;
  if (key !== lastDisplayKey) {
    lastDisplayKey = key;
    if (petWindow && !petWindow.isDestroyed()) {
      petWindow.webContents.send('display-config-changed', cfg);
    }
  }
}

function savePosition() {
  if (!petWindow || petWindow.isDestroyed()) return;
  const [x, y] = petWindow.getPosition();
  const [w, h] = petWindow.getSize();
  const d = safeDisplayMatching({ x: x, y: y, width: w, height: h });
  const wa = d.workArea;
  settings.position = {
    displayId: d.id,
    rx: (x - wa.x) / Math.max(wa.width - w, 1),
    ry: (y - wa.y) / Math.max(wa.height - h, 1),
  };
  saveSettings();
}

// ---- context menu ----
function sendCommand(cmd) {
  if (petWindow && !petWindow.isDestroyed()) {
    petWindow.webContents.send('pet-command', cmd);
  }
}

function applyOpacity() {
  if (petWindow && !petWindow.isDestroyed()) {
    petWindow.setOpacity(settings.opacity);
  }
}

function setOpacity(v) {
  settings.opacity = clamp(v, 0.3, 1);
  broadcastSettings();
  applyOpacity();
}

function resetPosition() {
  if (!petWindow || petWindow.isDestroyed()) return;
  const wa = screen.getPrimaryDisplay().workArea;
  const [w, h] = petWindow.getSize();
  petWindow.setBounds(clampToWorkArea({ x: wa.x + wa.width - w - 80, y: wa.y + wa.height - h - 40, width: w, height: h }));
  savePosition();
}

function toggleVisible() {
  if (!petWindow || petWindow.isDestroyed()) return;
  if (petWindow.isVisible()) {
    petWindow.hide();
    if (keyboardWindow && !keyboardWindow.isDestroyed()) keyboardWindow.hide();
  } else {
    petWindow.show();
    if (keyboardWindow && !keyboardWindow.isDestroyed()) keyboardWindow.show();
  }
}

function createContextMenu(currentActionId) {
  const actions = [
${menuItems}
  ];
  const items = actions.map(function (a) {
    return {
      label: a.id === currentActionId ? '\\u2713 ' + a.label : a.label,
      click: function () {
        if (petWindow) petWindow.webContents.send('switch-action', a.id);
      },
    };
  });
  items.push({ type: 'separator' });
  items.push({ label: '放大 (Ctrl+Shift+\\u2192)', click: function () { sendCommand('zoom-in'); } });
  items.push({ label: '缩小 (Ctrl+Shift+\\u2190)', click: function () { sendCommand('zoom-out'); } });
  items.push({ label: '恢复默认大小', click: function () { settings.zoom = 1; broadcastSettings(); } });
  items.push({ type: 'separator' });
  items.push({
    label: (settings.keyboardMode ? '\\u2713 ' : '') + '键盘模式（跟手打字键盘）',
    click: function () { setKeyboardMode(!settings.keyboardMode); },
  });
  items.push({ type: 'separator' });
  items.push({ label: '\\u9000\\u51fa', click: function () { app.quit(); } });
  return Menu.buildFromTemplate(items);
}

// ---- tray icon (fallback entry: show/hide + quit) ----
function createTray() {
  try {
    const iconPath = path.join(__dirname, 'assets', 'icon.png');
    const img = nativeImage.createFromPath(iconPath);
    const small = img.isEmpty() ? img : img.resize({ width: 16, height: 16 });
    tray = new Tray(small);
    tray.setToolTip(APP_NAME);
    tray.setContextMenu(Menu.buildFromTemplate([
      { label: '显示/隐藏', click: toggleVisible },
      { type: 'separator' },
      { label: '\\u9000\\u51fa', click: function () { app.quit(); } },
    ]));
    tray.on('click', toggleVisible);
  } catch (e) {
    console.warn('[pet] 托盘创建失败：', e.message);
  }
}

// ---- global input mirror (uiohook) ----
function initInputCapture() {
  if (!uiohook || !settings.inputMirror) return;
  let lastKeySentAt = 0;
  let lastKeyEventAt = 0;
  let lastClickSentAt = 0;
  try {
    uiohook.on('keydown', function () {
      // 键盘镜像只发给键盘模式窗口；持续输入期间每 1 秒补发一次，动画不间断
      const now = Date.now();
      if (now - lastKeyEventAt > 2000) lastKeySentAt = 0; // typing paused 2s -> reset cooldown
      lastKeyEventAt = now;
      if (now - lastKeySentAt >= 1000 && keyboardWindow && !keyboardWindow.isDestroyed()) {
        lastKeySentAt = now;
        keyboardWindow.webContents.send('input-event', { type: 'keydown' });
      }
    });
    uiohook.on('keyup', function () {
      lastKeyEventAt = Date.now();
    });
    uiohook.on('mousedown', function (e) {
      const now = Date.now();
      if (now - lastClickSentAt < 3000 || !petWindow || petWindow.isDestroyed()) return;
      // 点在桌宠/键盘窗口上的点击由它们自己的事件处理，不镜像
      if (clickInsideWindow(e, petWindow) || clickInsideWindow(e, keyboardWindow)) return;
      lastClickSentAt = now;
      petWindow.webContents.send('input-event', { type: 'mouse-down', button: e.button });
    });
    uiohook.start();
    console.log('[pet] 输入镜像已启用');
  } catch (e) {
    console.warn('[pet] 输入镜像启动失败：', e.message);
    uiohook = null;
  }
}

function clickInsideWindow(e, win) {
  if (!win || win.isDestroyed()) return false;
  const b = win.getBounds();
  return e.x >= b.x && e.x <= b.x + b.width && e.y >= b.y && e.y <= b.y + b.height;
}

// ---- keyboard mode window: BongoCat-style standalone typing mirror ----
// 独立小窗口（人物 + 手绘键盘），敲键盘时播 typing；窗口本身点击穿透，
// 固定主屏底部居中，不参与拖拽。窗口尺寸 480x370 与 keyboard.html 画布一致。
function createKeyboardWindow() {
  if (keyboardWindow && !keyboardWindow.isDestroyed()) return;
  const wa = screen.getPrimaryDisplay().workArea;
  const w = 480;
  const h = 370;
  keyboardWindow = new BrowserWindow({
    x: wa.x + Math.round((wa.width - w) / 2),
    y: wa.y + wa.height - h,
    width: w, height: h,
    transparent: true, frame: false, alwaysOnTop: true,
    skipTaskbar: true, resizable: false, hasShadow: false,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js'),
      contextIsolation: true, nodeIntegration: false,
    },
  });
  keyboardWindow.setIgnoreMouseEvents(true, { forward: true });
  keyboardWindow.loadFile(path.join(__dirname, 'renderer', 'keyboard.html'));
  attachErrorCapture(keyboardWindow, 'keyboard');
  keyboardWindow.on('closed', function () { keyboardWindow = null; });
}

function setKeyboardMode(v) {
  settings.keyboardMode = !!v;
  if (settings.keyboardMode) createKeyboardWindow();
  else if (keyboardWindow && !keyboardWindow.isDestroyed()) keyboardWindow.close();
  broadcastSettings();
}

// ---- IPC ----
ipcMain.on('show-context-menu', function (_event, currentActionId) {
  const menu = createContextMenu(currentActionId);
  menu.popup({ window: petWindow });
});

ipcMain.on('resize-window', function (_event, width, height) {
  if (!petWindow) return;
  width = Number(width);
  height = Number(height);
  if (!isFinite(width) || !isFinite(height) || width <= 0 || height <= 0) return;
  const [x, y] = petWindow.getPosition();
  const [w, h] = petWindow.getSize();
  // horizontal centering + bottom anchor (feet stay put, no jumping)
  petWindow.setBounds(clampToWorkArea({
    x: x + (w - width) / 2,
    y: y + (h - height),
    width: Math.round(width),
    height: Math.round(height),
  }));
});

ipcMain.on('move-window', function (_event, dx, dy, opts) {
  if (!petWindow) return;
  dx = Number(dx);
  dy = Number(dy);
  if (!isFinite(dx) || !isFinite(dy)) return;
  const [x, y] = petWindow.getPosition();
  let nx = x + dx;
  let ny = y + dy;
  if (opts && opts.clamp) {
    const [w, h] = petWindow.getSize();
    const b = clampToWorkArea({ x: nx, y: ny, width: w, height: h });
    nx = b.x;
    ny = b.y;
  }
  petWindow.setPosition(Math.round(nx), Math.round(ny));
});

ipcMain.handle('get-display-config', function () {
  return currentDisplayConfig();
});

ipcMain.handle('settings-get', function () {
  return settings;
});

ipcMain.on('settings-set', function (_event, patch) {
  if (!patch || typeof patch !== 'object') return;
  for (const k of Object.keys(patch)) settings[k] = patch[k];
  broadcastSettings();
});

ipcMain.handle('capabilities-get', function () {
  return {
    inputCapture: !!uiohook,
    opacity: settings.opacity,
  };
});

ipcMain.on('set-opacity', function (_event, v) {
  setOpacity(v);
});

ipcMain.on('quit-app', function () {
  app.quit();
});

// ---- global shortcuts ----
function registerShortcuts() {
  const SHORTCUTS = [
    ['Ctrl+Shift+B', toggleVisible],
    ['Ctrl+Shift+Left', function () { sendCommand('zoom-out'); }],
    ['Ctrl+Shift+Right', function () { sendCommand('zoom-in'); }],
    ['Ctrl+Shift+Up', function () { setOpacity(settings.opacity + 0.1); }],
    ['Ctrl+Shift+Down', function () { setOpacity(settings.opacity - 0.1); }],
    ['Ctrl+Shift+R', resetPosition],
    ['Ctrl+Shift+Q', function () { app.quit(); }],
  ];
  for (const pair of SHORTCUTS) {
    if (!globalShortcut.register(pair[0], pair[1])) {
      console.warn('[pet] 快捷键注册失败（可能被其他程序占用）：' + pair[0]);
    }
  }
}

// ---- app lifecycle ----
app.whenReady().then(function () {
  try {
    logStep('ready');
    createWindow();
    logStep('window-created');
    createTray();
    initInputCapture();
    registerShortcuts();
    if (settings.keyboardMode) createKeyboardWindow();
    logStep('startup-complete');
    screen.on('display-added', checkDisplayChange);
    screen.on('display-removed', checkDisplayChange);
    screen.on('display-metrics-changed', checkDisplayChange);
    app.on('activate', function () {
      if (BrowserWindow.getAllWindows().length === 0) createWindow();
    });
  } catch (e) {
    logError('whenReady', e);
  }
});

app.on('before-quit', function () {
  try {
    if (uiohook) uiohook.stop();
  } catch (e) { /* ignore */ }
  globalShortcut.unregisterAll();
  if (pendingSettingsSave) {
    clearTimeout(pendingSettingsSave);
    pendingSettingsSave = null;
  }
  try {
    fs.mkdirSync(userDataDir, { recursive: true });
    fs.writeFileSync(path.join(userDataDir, 'settings.json'), JSON.stringify(settings, null, 2));
  } catch (e) { /* ignore */ }
});

app.on('window-all-closed', function () {
  app.quit();
});
`;
}

function generatePackageJson(appName: string, appId: string) {
  return {
    name: 'desk-toy-custom',
    version: '1.0.0',
    description: appName,
    main: 'main.js',
    scripts: { start: 'electron .' },
    dependencies: {
      // N-API prebuilds — both load fine under Electron 28 (Node 18.18) without
      // rebuild, so @electron/rebuild is skipped entirely (it would try node-gyp
      // and fail on machines without Visual Studio).
      'uiohook-napi': '^1.5.5',
    },
    build: {
      appId,
      productName: appName,
      directories: { output: 'dist' },
      files: ['main.js', 'preload.js', 'renderer/**/*', 'sprites/**/*', 'assets/icon.png', 'assets/icon.icns'],
      asarUnpack: ['node_modules/uiohook-napi/**'],
      npmRebuild: false,
      mac: { target: ['dmg'], icon: 'assets/icon.icns', category: 'public.app-category.entertainment' },
      // signAndEditExecutable: false — 跳过 winCodeSign（exe 图标/元数据编辑）。
      // winCodeSign 需要从 GitHub 下载且解压需符号链接权限，国内网络/无开发者模式必失败。
      // 代价：exe 文件图标为默认 Electron 图标；托盘/任务栏图标来自 assets/icon.png 不受影响。
      win: { target: ['dir'], icon: 'assets/icon.png', signAndEditExecutable: false },
    },
    author: 'DeskToy',
    devDependencies: { electron: '28.3.3', 'electron-builder': '^25.0.0' },
  };
}

async function copyIfExists(src: string, dest: string) {
  try {
    await fs.copyFile(src, dest);
  } catch {}
}

async function removeGreenScreenForIcon(referencePath: string) {
  const image = sharp(referencePath).ensureAlpha();
  const metadata = await image.metadata();
  const width = metadata.width;
  const height = metadata.height;
  if (!width || !height) throw new Error('无法读取 reference.png 尺寸');

  const raw = await image.raw().toBuffer();
  for (let i = 0; i < raw.length; i += 4) {
    const r = raw[i];
    const g = raw[i + 1];
    const b = raw[i + 2];
    const maxOther = Math.max(r, b);
    const isGreen = g > 140 && g > maxOther * 1.25 && g - maxOther > 35;
    if (isGreen) {
      raw[i] = 0;
      raw[i + 1] = 255;
      raw[i + 2] = 0;
      raw[i + 3] = 0;
    }
  }

  return sharp(raw, { raw: { width, height, channels: 4 } }).png().toBuffer();
}

async function generateIconAssets(referencePath: string, assetsDir: string) {
  const iconPngPath = path.join(assetsDir, 'icon.png');
  const iconsetDir = path.join(assetsDir, 'icon.iconset');
  const iconsetSizes = [16, 32, 64, 128, 256, 512, 1024];
  const cleanedReference = await removeGreenScreenForIcon(referencePath);

  await sharp(cleanedReference)
    .resize(1024, 1024, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
    .png()
    .toFile(iconPngPath);

  try {
    await fs.mkdir(iconsetDir, { recursive: true });
    for (const size of iconsetSizes) {
      const buffer = await sharp(iconPngPath).resize(size, size).png().toBuffer();
      await fs.writeFile(path.join(iconsetDir, `icon_${size}x${size}.png`), buffer);
      if (size <= 512) {
        await fs.writeFile(path.join(iconsetDir, `icon_${size}x${size}@2x.png`), await sharp(iconPngPath).resize(size * 2, size * 2).png().toBuffer());
      }
    }
    await execFileAsync('iconutil', ['-c', 'icns', iconsetDir, '-o', path.join(assetsDir, 'icon.icns')]);
    await fs.rm(iconsetDir, { recursive: true, force: true });
  } catch {
    await copyIfExists(path.join(path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..'), 'assets', 'icon.icns'), path.join(assetsDir, 'icon.icns'));
  }
}

async function assertRequiredFiles(exportDir: string, actionIds: string[]) {
  const requiredFiles = [
    'main.js',
    'preload.js',
    'package.json',
    'renderer/index.html',
    'renderer/style.css',
    'renderer/actions.js',
    'renderer/sprite-engine.js',
    'renderer/app.js',
    'renderer/keyboard.html',
    'renderer/keyboard.js',
    ...actionIds.map((id) => `sprites/${id}.png`),
  ];

  const missing = [];
  for (const file of requiredFiles) {
    try {
      await fs.access(path.join(exportDir, file));
    } catch {
      missing.push(file);
    }
  }

  if (missing.length > 0) {
    throw new Error(`导出缺少必要文件：${missing.join(', ')}`);
  }
}

async function warnIfMacBuildIsUnsigned(exportDir: string, appName: string) {
  const appPath = path.join(exportDir, 'dist', 'mac', `${appName}.app`);
  try {
    await fs.access(appPath);
  } catch {
    return null;
  }

  try {
    await execFileAsync('codesign', ['--verify', '--deep', '--strict', appPath]);
    return null;
  } catch {
    return [
      `macOS 应用未签名：${appPath}`,
      '这类 DMG/APP 在本机可能能打开，但发给别人时常会被 Gatekeeper 拦截，表现为“打不开”或“已损坏”。',
      '解决方式：用 Apple Developer 证书签名并公证；仅自己测试时，可在系统设置 > 隐私与安全中允许打开，或手动移除隔离属性。',
    ].join('\n');
  }
}

async function main() {
  const args = parseArgs(process.argv);
  const sessionDir = args['session-dir'];
  const appName = args['app-name'] || '我的桌宠';
  const appId = args['app-id'] || 'com.desktoy.custom';
  const platform = args['platform'] || 'mac';
  const shouldBuild = args['build'] === 'true';

  if (!sessionDir) {
    console.error(JSON.stringify({
      success: false,
      error: 'Usage: npx tsx scripts/export-pet.ts --session-dir <path> [--app-name <name>] [--app-id <id>] [--platform mac|win|all] [--build]',
    }));
    process.exit(1);
  }

  const projectRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
  const actionsPath = path.join(sessionDir, 'actions.json');
  const referencePath = path.join(sessionDir, 'reference.png');
  const characterPath = path.join(sessionDir, 'character.json');
  const spritesDir = path.join(sessionDir, 'sprites');
  const exportDir = path.join(sessionDir, 'export');

  const allActions: ActionDefinition[] = JSON.parse(await fs.readFile(actionsPath, 'utf-8'));
  const readyActions = allActions.filter((a) => a.spriteReady);

  // Persona for the AI chat system prompt (baked from character.json, no secrets)
  let persona: unknown = { name: appName };
  try {
    persona = JSON.parse(await fs.readFile(characterPath, 'utf-8'));
  } catch {
    persona = { name: appName };
  }

  if (readyActions.length === 0) {
    console.error(JSON.stringify({ success: false, error: '没有已完成的精灵图' }));
    process.exit(1);
  }

  try {
    await fs.rm(exportDir, { recursive: true, force: true });
  } catch {
    // Windows: another process (杀软扫描/残留 CWD) may hold a handle on the dir
    // object itself even though its contents are free — clear contents best-effort
    // and reuse the directory instead of failing the whole export.
    const entries = await fs.readdir(exportDir, { withFileTypes: true });
    await Promise.allSettled(
      entries.map((e) => fs.rm(path.join(exportDir, e.name), { recursive: true, force: true }))
    );
  }
  for (const sub of ['renderer', 'sprites', 'assets']) {
    await fs.mkdir(path.join(exportDir, sub), { recursive: true });
  }

  await fs.copyFile(path.join(projectRoot, 'preload.js'), path.join(exportDir, 'preload.js'));
  for (const f of ['index.html', 'style.css', 'sprite-engine.js', 'app.js', 'keyboard.html', 'keyboard.js']) {
    await copyIfExists(path.join(projectRoot, 'renderer', f), path.join(exportDir, 'renderer', f));
  }
  await generateIconAssets(referencePath, path.join(exportDir, 'assets'));

  for (const action of readyActions) {
    const src = path.join(spritesDir, `${action.id}.png`);
    await copyIfExists(src, path.join(exportDir, 'sprites', `${action.id}.png`));
  }

  await fs.writeFile(path.join(exportDir, 'renderer', 'actions.js'), generateActionsJs(readyActions));
  await fs.writeFile(path.join(exportDir, 'main.js'), generateMainJs(readyActions, persona, appName));
  await fs.writeFile(path.join(exportDir, 'package.json'), JSON.stringify(generatePackageJson(appName, appId), null, 2));
  await assertRequiredFiles(exportDir, readyActions.map((action) => action.id));

  console.log(JSON.stringify({ success: true, exportDir, actions: readyActions.length }));

  if (shouldBuild) {
    const target = platform === 'win' ? '--win' : platform === 'all' ? '--mac --win' : '--mac';
    console.error(`Installing dependencies...`);
    await execAsync('npm install', { cwd: exportDir });
    console.error(`Building with electron-builder ${target}...`);
    const { stdout } = await execAsync(`npx electron-builder ${target}`, { cwd: exportDir, timeout: 300000 });
    const macSigningWarning = target.includes('--mac') ? await warnIfMacBuildIsUnsigned(exportDir, appName) : null;
    if (macSigningWarning) {
      console.error(macSigningWarning);
    }
    console.log(JSON.stringify({ success: true, built: true, stdout: stdout.slice(-500), macSigningWarning }));
  }
}

main().catch((err) => {
  console.error(JSON.stringify({ success: false, error: err.message }));
  process.exit(1);
});
